"""
Report Service.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.core.logger import logger
from app.db.repositories.report_repository import ReportRepository
from app.models.report import (
    Report,
    ReportStatus,
)
from app.schemas.report import (
    ReportCreate,
)


class ReportService:
    """
    Business logic for Report management.
    """

    repository = ReportRepository()

    @classmethod
    def create(
        cls,
        db: Session,
        request: ReportCreate,
    ) -> Report:

        if request.report_period_start > request.report_period_end:
            raise ValueError(
                "Report start date must be before end date."
            )

        report = Report(
            **request.model_dump(),
            generated_at=datetime.now(timezone.utc),
            report_status=ReportStatus.GENERATED,
        )

        logger.info(
            "Report '%s' generated by %s.",
            request.report_name,
            request.generated_by,
        )

        return cls.repository.create(
            db,
            report,
        )

    @classmethod
    def get_by_id(
        cls,
        db: Session,
        report_id: int,
    ) -> Report | None:

        return cls.repository.get_by_id(
            db,
            report_id,
        )

    @classmethod
    def get_reports(
        cls,
        db: Session,
        **kwargs,
    ) -> list[Report]:

        return cls.repository.get_reports(
            db,
            **kwargs,
        )

    @classmethod
    def get_summary(
        cls,
        db: Session,
        report_id: int,
    ) -> dict:

        report = cls.repository.get_by_id(
            db,
            report_id,
        )

        if report is None:
            raise ValueError(
                "Report not found."
            )

        return cls.repository.get_summary(
            db,
        )

    @classmethod
    def delete(
        cls,
        db: Session,
        report_id: int,
    ) -> Report:

        report = cls.repository.get_by_id(
            db,
            report_id,
        )

        if report is None:
            raise ValueError(
                "Report not found."
            )

        logger.info(
            "Report %s deleted.",
            report.id,
        )

        return cls.repository.soft_delete(
            db,
            report,
        )