"""Create infrastructure assets table

Revision ID: 08f26877de31
Revises: eecef2d9e0ac
Create Date: 2026-08-04 18:06:59.003637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f26877de31'
down_revision: Union[str, Sequence[str], None] = 'eecef2d9e0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_assets',
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('operating_system', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.Enum('SERVER', 'VM', 'DOCKER_HOST', name='asset_type_enum'), nullable=False),
    sa.Column('environment', sa.Enum('DEVELOPMENT', 'STAGING', 'PRODUCTION', name='environment_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', 'OFFLINE', name='asset_status_enum'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_infrastructure_assets_hostname'), 'infrastructure_assets', ['hostname'], unique=False)
    op.create_index(op.f('ix_infrastructure_assets_id'), 'infrastructure_assets', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_assets_ip_address'), 'infrastructure_assets', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_infrastructure_assets_ip_address'), table_name='infrastructure_assets')
    op.drop_index(op.f('ix_infrastructure_assets_id'), table_name='infrastructure_assets')
    op.drop_index(op.f('ix_infrastructure_assets_hostname'), table_name='infrastructure_assets')
    op.drop_table('infrastructure_assets')
    # ### end Alembic commands ###
