"""add is_active to monitoring agents

Revision ID: 35467fb8989b
Revises: efaf1339e012
Create Date: 2026-08-05 13:07:28.902379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35467fb8989b'
down_revision: Union[str, Sequence[str], None] = 'efaf1339e012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_agents', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_agents', 'is_active')
    # ### end Alembic commands ###
