"""create reports table

Revision ID: 3a9bc4792aaf
Revises: 4f0725a55014
Create Date: 2026-08-05 18:04:12.246816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9bc4792aaf'
down_revision: Union[str, Sequence[str], None] = '4f0725a55014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('INFRASTRUCTURE', 'METRICS', 'INCIDENTS', 'ALERTS', 'LOGS', 'EXECUTIVE', name='report_type_enum', native_enum=False), nullable=False),
    sa.Column('generated_by', sa.String(length=255), nullable=False),
    sa.Column('report_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_status', sa.Enum('PENDING', 'GENERATED', 'FAILED', name='report_status_enum', native_enum=False), nullable=False),
    sa.Column('report_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
