"""create alerts table

Revision ID: 5f29acb5886e
Revises: 63a8f0a5cebd
Create Date: 2026-08-05 16:05:01.129313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f29acb5886e'
down_revision: Union[str, Sequence[str], None] = '63a8f0a5cebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('infrastructure_asset_id', sa.Integer(), nullable=False),
    sa.Column('monitoring_agent_id', sa.Integer(), nullable=False),
    sa.Column('system_metric_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('alert_title', sa.String(length=255), nullable=False),
    sa.Column('alert_description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status_enum'), nullable=False),
    sa.Column('metric_name', sa.Enum('CPU', 'MEMORY', 'DISK', 'NETWORK', 'CUSTOM', name='metric_type_enum'), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['infrastructure_asset_id'], ['infrastructure_assets.id'], ),
    sa.ForeignKeyConstraint(['monitoring_agent_id'], ['monitoring_agents.id'], ),
    sa.ForeignKeyConstraint(['system_metric_id'], ['system_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_incident_id'), 'alerts', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alerts_infrastructure_asset_id'), 'alerts', ['infrastructure_asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_monitoring_agent_id'), 'alerts', ['monitoring_agent_id'], unique=False)
    op.create_index(op.f('ix_alerts_system_metric_id'), 'alerts', ['system_metric_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_system_metric_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_monitoring_agent_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_infrastructure_asset_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
