"""create incidents table

Revision ID: 63a8f0a5cebd
Revises: ec08548dc4b2
Create Date: 2026-08-05 15:48:29.871357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a8f0a5cebd'
down_revision: Union[str, Sequence[str], None] = 'ec08548dc4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('infrastructure_asset_id', sa.Integer(), nullable=False),
    sa.Column('monitoring_agent_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('incident_title', sa.String(length=255), nullable=False),
    sa.Column('incident_description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='incident_status_enum'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_asset_id'], ['infrastructure_assets.id'], ),
    sa.ForeignKeyConstraint(['monitoring_agent_id'], ['monitoring_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_infrastructure_asset_id'), 'incidents', ['infrastructure_asset_id'], unique=False)
    op.create_index(op.f('ix_incidents_monitoring_agent_id'), 'incidents', ['monitoring_agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_monitoring_agent_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_infrastructure_asset_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
