"""create automation rules table

Revision ID: 8217c365a019
Revises: 3a9bc4792aaf
Create Date: 2026-08-05 18:09:30.299989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8217c365a019'
down_revision: Union[str, Sequence[str], None] = '3a9bc4792aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric_type', sa.Enum('CPU_USAGE', 'MEMORY_USAGE', 'DISK_USAGE', 'NETWORK_USAGE', 'LOG_ERROR_RATE', 'INCIDENT_COUNT', name='metric_type_enum', native_enum=False), nullable=False),
    sa.Column('operator', sa.Enum('GT', 'GTE', 'LT', 'LTE', 'EQ', 'NE', name='rule_operator_enum', native_enum=False), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='rule_severity_enum', native_enum=False), nullable=False),
    sa.Column('action_type', sa.Enum('CREATE_ALERT', 'CREATE_INCIDENT', 'RESTART_SERVICE', 'RESTART_CONTAINER', 'REBOOT_SERVER', 'SCALE_SERVICE', 'SEND_NOTIFICATION', name='action_type_enum', native_enum=False), nullable=False),
    sa.Column('target_scope', sa.Enum('GLOBAL', 'ASSET', 'AGENT', name='target_scope_enum', native_enum=False), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index(op.f('ix_automation_rules_id'), 'automation_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_automation_rules_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
