"""move is_active to base model

Revision ID: e0f2e59a21c8
Revises: d52ccd621ca8
Create Date: 2026-08-05 18:19:04.801689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f2e59a21c8'
down_revision: Union[str, Sequence[str], None] = 'd52ccd621ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('incidents', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('reports', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('system_logs', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('system_metrics', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_metrics', 'is_active')
    op.drop_column('system_logs', 'is_active')
    op.drop_column('reports', 'is_active')
    op.drop_column('notifications', 'is_active')
    op.drop_column('incidents', 'is_active')
    op.drop_column('alerts', 'is_active')
    # ### end Alembic commands ###
