"""create monitoring agents table

Revision ID: efaf1339e012
Revises: 08f26877de31
Create Date: 2026-08-05 12:44:38.703384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaf1339e012'
down_revision: Union[str, Sequence[str], None] = '08f26877de31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_agents',
    sa.Column('infrastructure_asset_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=150), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('registration_token', sa.String(length=255), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='agent_status_enum', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_asset_id'], ['infrastructure_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_token')
    )
    op.create_index(op.f('ix_monitoring_agents_id'), 'monitoring_agents', ['id'], unique=False)
    op.create_index(op.f('ix_monitoring_agents_infrastructure_asset_id'), 'monitoring_agents', ['infrastructure_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_agents_infrastructure_asset_id'), table_name='monitoring_agents')
    op.drop_index(op.f('ix_monitoring_agents_id'), table_name='monitoring_agents')
    op.drop_table('monitoring_agents')
    # ### end Alembic commands ###
