"""create system logs table

Revision ID: ff77680abffe
Revises: 5f29acb5886e
Create Date: 2026-08-05 16:43:32.253340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff77680abffe'
down_revision: Union[str, Sequence[str], None] = '5f29acb5886e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('infrastructure_asset_id', sa.Integer(), nullable=False),
    sa.Column('monitoring_agent_id', sa.Integer(), nullable=False),
    sa.Column('log_level', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level_enum', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['infrastructure_asset_id'], ['infrastructure_assets.id'], ),
    sa.ForeignKeyConstraint(['monitoring_agent_id'], ['monitoring_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_event_timestamp'), 'system_logs', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_infrastructure_asset_id'), 'system_logs', ['infrastructure_asset_id'], unique=False)
    op.create_index(op.f('ix_system_logs_monitoring_agent_id'), 'system_logs', ['monitoring_agent_id'], unique=False)
    op.drop_column('incidents', 'alert_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('alert_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_system_logs_monitoring_agent_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_infrastructure_asset_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_event_timestamp'), table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
